Models/KafkaMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FXPostgres.Models
{
    public class KafkaMessage
    {
        public string message { get; set; }
        public string topic { get; set; }
        public int offset { get; set; }
        public int partition { get; set; }
    }
}

Controllers/PostgresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using FXPostgres.Models;
using Npgsql;
using System.Text;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace FXPostgres.Controllers
{
    public class PostgresController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.ClientID = ConfigVars.Instance.clientID;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> ReadKafkaMessage(string eventSource, bool isReadFromFirst)
        {
            try
            {
                int lastOffset = -1;
                if (!isReadFromFirst)
                    lastOffset = getLastKafkaOffset();

                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Accept.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpRequestMessage request = new HttpRequestMessage
                    {
                        Method = HttpMethod.Get,
                        RequestUri = new Uri(string.Format("{0}", ConfigVars.Instance.EnpointUrl))
                    };
                    var response = await httpClient.SendAsync(request);
                    if (response.IsSuccessStatusCode)
                    {
                        var kafkaResponse = await response.Content.ReadAsStringAsync();
                        var kafkaMessage = JsonConvert.DeserializeObject<List<KafkaMessage>>(kafkaResponse);
                        if (kafkaMessage != null)
                        {
                            if (isReadFromFirst && kafkaMessage.Where(p => p.offset > 0 && p.topic.ToUpper() == ConfigVars.Instance.KafkaTopic.ToUpper()).Count() > 0)
                                return Json(kafkaMessage.Where(p => p.offset > 0 && p.topic.ToUpper() == ConfigVars.Instance.KafkaTopic.ToUpper()).ToList());
                            else if (kafkaMessage.Where(p => p.offset > lastOffset && p.topic.ToUpper() == ConfigVars.Instance.KafkaTopic.ToUpper()).Count() > 0)
                                return Json(kafkaMessage.Where(p => p.offset > lastOffset && p.topic.ToUpper() == ConfigVars.Instance.KafkaTopic.ToUpper()).ToList());
                        }
                    }

                    return Json(null);
                }
            }
            catch (Exception exception)
            {
                return Json(null);
            }
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<JsonResult> WriteKafkaMessage(List<KafkaMessage> kafkaMessage, bool isWriteFromFirst)
        {
            try
            {
                int lastOffset = -1;
                if (!isWriteFromFirst)
                {
                    lastOffset = getLastKafkaOffset();
                    kafkaMessage = kafkaMessage.Where(p => p.offset > lastOffset).ToList();
                }
                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    if (isWriteFromFirst)
                    {
                        using (NpgsqlCommand cmd = new NpgsqlCommand("delete from fxvip;", sqlCon))
                        {
                            cmd.ExecuteNonQuery();
                        }
                    }
                }

                for (int i = 0; i < kafkaMessage.Count; i++)
                {
                    using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                    {
                        sqlCon.Open();
                        using (NpgsqlCommand cmd = new NpgsqlCommand(string.Format("insert into fxvip(\"Offset\",\"Message\",\"Topic\",\"Partition\")values('{0}','{1}','{2}','{3}');", kafkaMessage[i].offset, kafkaMessage[i].message, kafkaMessage[i].topic, kafkaMessage[i].partition), sqlCon))
                        {
                            cmd.ExecuteNonQuery();
                        }
                    }
                }

                return Json("success");
            }
            catch (Exception exception)
            {
                return Json(exception.Message);
            }
        }

        public IActionResult Error()
        {
            return View();
        }

        private int getLastKafkaOffset()
        {
            var offset = -1;
            try
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("select coalesce(max(\"Offset\"),0) as maxoffset from fxvip;");
                using (var sqlCon = new NpgsqlConnection(ConfigVars.Instance.PostgresDBConnectionString))
                {
                    sqlCon.Open();
                    using (NpgsqlCommand cmd = new NpgsqlCommand(sb.ToString(), sqlCon))
                    {
                        using (NpgsqlDataReader reader = cmd.ExecuteReader())
                        {
                            while (reader.HasRows)
                            {
                                while (reader.Read())
                                {
                                    int.TryParse(reader["maxoffset"].ToString(), out offset);
                                    ViewBag.LastOffset = offset;
                                }

                                if (reader.NextResult() == false)
                                    break;
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {

            }

            return offset;
        }
    }
}

Views/Postgres/Index.cshtml
@{
    ViewData["Title"] = "Web Traffic";
}

<div class="container-fluid" style="padding:0px;margin-top:1%;">
    <div class="col-md-12" style="padding:0px;">
        <div class="col-md-3" style="padding-left:0px;">
            <label for="clientID" style="float:left;margin-right:2%;line-height:35px;">TrackingID</label>
            <input style="width:40%;" type="text" class="form-control" id="clientID" value="@String.Format("{0:n0}", ViewBag.ClientID)">
        </div>
        <div class="col-lg-3" style="padding-left:0px;">
            <label for="trafficUrl" style="float:left;margin-right:2%;line-height:35px;">Event Source</label>
            <select class="dropdown" style="width:50%;padding:6px; vertical-align:middle;">
                <option value="LandingPage">LandingPage</option>
                <option value="FacebookTab">FacebookTab</option>
                <option value="Microsite">Microsite</option>
                <option value="Web">Web</option>
            </select>
        </div>
    </div>
    <div class="col-md-12" style="padding:0px;margin-top:2%;vertical-align:middle">
        <div class="col-md-5" style="padding:0px;">
            <p style="text-align:center;font-weight:bold;">Kafka Topic (messages)</p>
            <div class="table-responsive" style="max-height:450px;overflow-y: auto;padding:0px;">
                <table id="kafkaDataTable" class="table-bordered" style="width:100%;min-height:450px;"></table>
            </div>
            <p style="text-align:center;font-weight:bold;color:#4c4691;margin-top:10px;" id="kafkaMessage">&nbsp;</p>
        </div>
        <div class="col-md-2" style="height:400px;margin-top:13%;">
            <input id="btnReadFromFirst" type="button" value="Read from offset 0" class="btn-custom" style="width:100%;" />
            <input id="btnReadFromLast" type="button" value="Read from last offset" class="btn-custom" style="width:100%;margin-top:10%;" />
            <input id="btnWriteFromFirst" type="button" value="Write from offset 0" class="btn-custom" style="width:100%;margin-top:10%;" />
            <input id="btnWriteFromLast" type="button" value="Write from last offset" class="btn-custom" style="width:100%;margin-top:10%;" />
        </div>
        <div class="col-md-5" style="padding:0px">
            <p style="text-align:center;font-weight:bold;">Postgres DB (fxvip table)</p>
            <div class="table-responsive" style="max-height:450px;overflow-y: auto;padding:0px;">
                <table id="postgresDataTable" class="table-bordered" style="width:100%;min-height:450px;"></table>
            </div>
            <p style="text-align:center;font-weight:bold;color:green;margin-top:10px;" id="postgresMessage">&nbsp;</p>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var urlReadAction = '/Postgres/ReadKafkaMessage';
        var urlWriteAction = '/Postgres/WriteKafkaMessage';
        var isSentData = false;
        var startProcess, btnText, btnBgColor;
        var kafkaMessage = [], isReadFromFirst = false, isWriteFromFirst = false;

        $(function () {
            $('#spinner').hide();
            bindTrafficDataTable(true);
            bindTrafficDataTable(false);
            $('#btnReadFromFirst').on('click', function (e) {
                isReadFromFirst = true;
                setActiveButtonBG($(this));
                resetTrafficTable(true);
                resetTrafficTable(false);
                readKafkaMessage();
            });
            $('#btnReadFromLast').on('click', function (e) {
                isReadFromFirst = false;
                setActiveButtonBG($(this));
                resetTrafficTable(true);
                resetTrafficTable(false);
                readKafkaMessage();
            });
            $('#btnWriteFromFirst').on('click', function (e) {
                if (kafkaMessage == undefined || (kafkaMessage && kafkaMessage.length == 0))
                    return;
                isWriteFromFirst = true;
                setActiveButtonBG($(this));
                resetTrafficTable(false);
                writeKafkaMessage();
            });
            $('#btnWriteFromLast').on('click', function (e) {
                if (kafkaMessage == undefined || (kafkaMessage && kafkaMessage.length == 0))
                    return;
                isWriteFromFirst = false;
                setActiveButtonBG($(this));
                resetTrafficTable(false);
                writeKafkaMessage();
            });
        });

        function setActiveButtonBG(activeButton) {
            $('input[type=button]').each(function () {
                if ($(this).attr('id') == activeButton.attr('id'))
                    $(this).addClass('btn-custom2');
                else {
                    $(this).removeClass('btn-custom2');
                }
            })
        }
        function resetTrafficTable(isKafka) {
            var trafficTable = isKafka ? $('#kafkaDataTable') : $('#postgresDataTable');
            trafficTable.find("tr").remove();
            if (isKafka)
                $('#kafkaMessage').html('');
            else
                $('#postgresMessage').html('');
        }

        function bindTrafficDataTable(isKafka) {
            var tableDataRow;
            var trafficTable = isKafka ? $('#kafkaDataTable') : $('#postgresDataTable');
            tableDataRow = trafficTable.find("tr:gt(0)");
            if (kafkaMessage && kafkaMessage.length > 0) {
                tableDataRow.find('tr').remove();
                for (var i = 0; i < kafkaMessage.length; i++) {
                    if (kafkaMessage[i].message) {
                        trafficTable.append("<tr><td style='border-bottom: 1px solid #ddd;'><div class='wrapword'>" + kafkaMessage[i].message + "</div></td></tr>");
                        tableDataRow = trafficTable.find("tr:gt(0)");
                    }
                }
                if (isKafka) {
                    if (isReadFromFirst)
                        $('#kafkaMessage').html('Messages from offset 0 (All ' + kafkaMessage.length + ')');
                    else
                        $('#kafkaMessage').html('Messages ' + kafkaMessage[0].offset + ' - ' + kafkaMessage[kafkaMessage.length - 1].offset + '(' + kafkaMessage.length + ' Messages)');
                }
                else {
                    if (isWriteFromFirst)
                        $('#postgresMessage').html('Write all from offset 0 to ' + kafkaMessage.length + ' to Postgres');
                    else
                        $('#postgresMessage').html('Write from ' + kafkaMessage[0].offset + ' to ' + kafkaMessage[kafkaMessage.length - 1].offset + ' to Postgres');
                }
            }
            if (tableDataRow.length == 0) {
                tableDataRow.remove();
                trafficTable.append("<tr class='emptyrow'><td style='text-align:center;'>No Record Found</td></tr>");
            }
        }
        function readKafkaMessage() {
            kafkaMessage = [];
            $('#spinner').show();
            $.post(urlReadAction, { eventSource: $('.dropdown').val(), isReadFromFirst: isReadFromFirst }, function (data) {
                $('#spinner').hide();
                kafkaMessage = data;
                bindTrafficDataTable(true)
            });
        }
        function writeKafkaMessage() {
            $('#spinner').show();
            $.post(urlWriteAction, { kafkaMessage: kafkaMessage, isWriteFromFirst: isWriteFromFirst }, function (data) {
                $('#spinner').hide();
                console.log(data);
                if (data == "success") {
                    bindTrafficDataTable(false)
                }
            });
        }
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kafka to Postgres Consumer</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style type="text/css">
        .container-full-screen {
            margin: 0 auto;
            width: 100%;
        }
    </style>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-full-screen">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="javascript:void(0);" class="navbar-brand">Heroku</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Postgres" asp-action="Index">Kafka to Postgres Consumer</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-full-screen body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><a href="mailto:david@heroku.com">david@heroku.com</a> to find out more about this app</p>
        </footer>
    </div>
    <div id="spinner" style="display:block;"></div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#spinner').hide();
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>